// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoWeb.Data;

namespace ProjetoWeb.Migrations
{
    [DbContext(typeof(AplicationDbContext))]
    [Migration("20210319185712_MudancaNasTabelas")]
    partial class MudancaNasTabelas
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProjetoWeb.Models.Especialidades", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Codigo");

                    b.Property<string>("NomeDaEspecialidade")
                        .IsRequired();

                    b.Property<int?>("ProfissionaisId");

                    b.HasKey("Id");

                    b.HasIndex("ProfissionaisId");

                    b.ToTable("especialidades");
                });

            modelBuilder.Entity("ProjetoWeb.Models.Profissionais", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bairro")
                        .IsRequired();

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasMaxLength(8);

                    b.Property<string>("Cidade")
                        .IsRequired();

                    b.Property<string>("Complemento")
                        .IsRequired();

                    b.Property<int>("EspecialidadeIDId");

                    b.Property<DateTime>("Nascimento");

                    b.Property<string>("Nome")
                        .IsRequired();

                    b.Property<string>("Rua")
                        .IsRequired();

                    b.Property<string>("Telefone")
                        .IsRequired();

                    b.Property<string>("UF")
                        .IsRequired();

                    b.Property<string>("WhatsApp")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("EspecialidadeIDId");

                    b.ToTable("Profissionais");
                });

            modelBuilder.Entity("ProjetoWeb.Models.Especialidades", b =>
                {
                    b.HasOne("ProjetoWeb.Models.Profissionais")
                        .WithMany("Especialidades")
                        .HasForeignKey("ProfissionaisId");
                });

            modelBuilder.Entity("ProjetoWeb.Models.Profissionais", b =>
                {
                    b.HasOne("ProjetoWeb.Models.Especialidades", "EspecialidadeID")
                        .WithMany()
                        .HasForeignKey("EspecialidadeIDId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
