// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoWeb.Data;

namespace ProjetoWeb.Migrations
{
    [DbContext(typeof(AplicationDbContext))]
    [Migration("20210323185834_modificacaoDB")]
    partial class modificacaoDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProjetoWeb.Models.Especialidades", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Codigo");

                    b.Property<string>("NomeDaEspecialidade")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Especialidades");
                });

            modelBuilder.Entity("ProjetoWeb.Models.ModelsDB.ProfissionaisEspecialidadesFK", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("EspecialidadesId");

                    b.Property<int?>("ProfissionaisId");

                    b.HasKey("Id");

                    b.HasIndex("EspecialidadesId");

                    b.HasIndex("ProfissionaisId");

                    b.ToTable("ProfissionaisEspecialidadesFK");
                });

            modelBuilder.Entity("ProjetoWeb.Models.Profissionais", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bairro")
                        .IsRequired();

                    b.Property<int>("CEP");

                    b.Property<string>("Cidade")
                        .IsRequired();

                    b.Property<string>("Complemento")
                        .IsRequired();

                    b.Property<DateTime>("Nascimento");

                    b.Property<string>("Nome")
                        .IsRequired();

                    b.Property<string>("Rua")
                        .IsRequired();

                    b.Property<string>("Telefone")
                        .IsRequired();

                    b.Property<string>("UF")
                        .IsRequired();

                    b.Property<string>("WhatsApp")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Profissionais");
                });

            modelBuilder.Entity("ProjetoWeb.Models.ModelsDB.ProfissionaisEspecialidadesFK", b =>
                {
                    b.HasOne("ProjetoWeb.Models.Especialidades", "Especialidades")
                        .WithMany("ProfissionaisEspecialidadesFK")
                        .HasForeignKey("EspecialidadesId");

                    b.HasOne("ProjetoWeb.Models.Profissionais", "Profissionais")
                        .WithMany("ProfissionaisEspecialidadesFK")
                        .HasForeignKey("ProfissionaisId");
                });
#pragma warning restore 612, 618
        }
    }
}
